// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHLyLIR55F2ey83L1RHtHHiPijsrIxjXQ',
    appId: '1:1432230106:android:3249d496888bb9021e2de3',
    messagingSenderId: '1432230106',
    projectId: 'coffeapp-e53f7',
    storageBucket: 'coffeapp-e53f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG1sJ1_cZ1dUXYTrmTPvEIkYhQS1qcfp8',
    appId: '1:1432230106:ios:cf65d2f62559448f1e2de3',
    messagingSenderId: '1432230106',
    projectId: 'coffeapp-e53f7',
    storageBucket: 'coffeapp-e53f7.appspot.com',
    androidClientId: '1432230106-stflmuq9p55lj1sr8rvj3hj0k3rmvkav.apps.googleusercontent.com',
    iosClientId: '1432230106-5cvpd8sku9ivrfhrasjbl7ndgu37mt0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeApp',
  );

}